/**
 * Centralized permission matrix for ClassAssist Pro.
 * All permission checks flow through this module.
 */

export const PERMISSIONS = {
  CREATE_CLASS: "CREATE_CLASS",
  EDIT_CLASS: "EDIT_CLASS",
  DELETE_CLASS: "DELETE_CLASS",
  VIEW_CLASSES: "VIEW_CLASSES",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_SUBSCRIPTION: "MANAGE_SUBSCRIPTION",
  SEND_REMINDER: "SEND_REMINDER",
  MANAGE_STUDENTS: "MANAGE_STUDENTS",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",
  VOICE_COMMAND: "VOICE_COMMAND",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type Role = "ADMIN" | "MANAGER" | "TEACHER";

/** Role -> permissions. ADMIN has platform-level permissions; TEACHER/MANAGER are tenant-scoped. */
const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    PERMISSIONS.PLATFORM_ADMIN,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_SUBSCRIPTION,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.EDIT_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.SEND_REMINDER,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VOICE_COMMAND,
  ],
  MANAGER: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.EDIT_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.SEND_REMINDER,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VOICE_COMMAND,
  ],
  TEACHER: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.EDIT_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.SEND_REMINDER,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VOICE_COMMAND,
  ],
};

export function hasPermission(role: string, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role as Role];
  if (!permissions) return false;
  return permissions.includes(permission);
}

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
